export { Avatar } from "./Avatar";
export { AvatarFallback } from "./avatar-fallback/AvatarFallback";
export { AvatarIcon } from "./avatar-icon/AvatarIcon";
export { AvatarImage } from "./avatar-image/AvatarImage";
export { AvatarLabel } from "./avatar-label/AvatarLabel";
export { AvatarLabelAvatar } from "./avatar-label/components/avatar-label-avatar/AvatarLabelAvatar";
export { AvatarLabelIndicator } from "./avatar-label/components/avatar-label-indicator/AvatarLabelIndicator";
export { AvatarLabelTitle } from "./avatar-label/components/avatar-label-title/AvatarLabelTitle";
export { AvatarLabelDescription } from "./avatar-label/components/avatar-label-description/AvatarLabelDescription";
export { useAvatarLabelContext } from "./avatar-label/AvatarLabelContext";
export type { AvatarLabelComponentType, AvatarLabelChild } from "./avatar-label/AvatarLabelContext";
